import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar'
import './globals.css'
import { getServerSession } from 'next-auth'
// import SessionProvider from "./components/SessionProvider"
import Authprovider from './components/Authprovider'
// import Navmenu from './components/navmenu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-medium`}>

      {/* <SessionProvider session={session}> */}
      <Authprovider>
      <div className=' mx-auto mt-3'>
      <Navbar/>
      {/* <Navmenu/> */}
        {children}
        </div>
        </Authprovider>
      {/* </SessionProvider> */}
        </body>
    </html>
  )
}
